### ISSUE TITLE
merge/override results in duplicate keys

### ISSUE THREAD

**Issue by dinurp** [sclevine/yj#48]
[Merge/Overriding](https://yaml.org/type/merge.html) results in duplicate keys

Input Yaml
```
templates:
  default: &default
    labels:
      sync: everyday
charts:
  - name: test
    <<: *default
    chart: test
    labels:
      sync: thur
```
from: https://github.com/roboll/helmfile/issues/657

with `yj -yy` results in

Output Yaml 
```
templates:
  default:
    labels:
      sync: everyday
charts:
  - name: test
    labels:
      sync: everyday
    chart: test
    labels:
      sync: thur
```
Note that the key `labels/sync` is duplicate; it should have overwritten the original value.
