### ISSUE TITLE
converting null value to empty string

### ISSUE THREAD

**Issue by sudeeshjohn** [sclevine/yj#6]
When its converting yaml which have null as value to HCL replacing the value as empty string which is failing in terraform validation

```
klusterle:
  host: null
prometheusInteg:
  enabled: true
```

HCL:
```
"klusterle" = {
  "host" =
}

"prometheusInteg" = {
  "enabled" = true
```
